-- MySQL Script generated by MySQL Workbench
-- Fri May  4 16:59:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LuchtvaartmaatschappijGAII
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LuchtvaartmaatschappijGAII`
;

-- -----------------------------------------------------
-- Schema LuchtvaartmaatschappijGAII
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `LuchtvaartmaatschappijGAII` DEFAULT CHARACTER
SET utf8 ;
USE `LuchtvaartmaatschappijGAII`
;

-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`Vlucht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`Vlucht` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`Vlucht`
(
  `vluchtNr` VARCHAR
(45) NOT NULL,
  `datum` DATE NOT NULL,
  PRIMARY KEY
(`vluchtNr`, `datum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`VliegtuigType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`VliegtuigType` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`VliegtuigType`
(
  `type` VARCHAR
(45) NOT NULL,
  `maxLading` INT NULL,
  PRIMARY KEY
(`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`Vliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`Vliegtuig` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`Vliegtuig`
(
  `registratieNr` VARCHAR
(45) NOT NULL,
  `type` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`registratieNr`),
  INDEX `fk_JiSQL6_idx`
(`type` ASC),
  CONSTRAINT `fk_JiSQL6`
    FOREIGN KEY
(`type`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`VliegtuigType`
(`type`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`PassagiersVliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`PassagiersVliegtuig` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`PassagiersVliegtuig`
(
  `aantalStewardessen` INT NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`registratieNr`),
  CONSTRAINT `fk_JiSQL2`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`Vliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`Passagiersvlucht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`Passagiersvlucht` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`Passagiersvlucht`
(
  `onverkochteStoelen` INT NOT NULL,
  `vluchtNr` VARCHAR
(45) NOT NULL,
  `datum` DATE NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`vluchtNr`, `datum`),
  INDEX `fk_JiSQL4_idx`
(`registratieNr` ASC),
  CONSTRAINT `fk_JiSQL`
    FOREIGN KEY
(`vluchtNr` , `datum`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`Vlucht`
(`vluchtNr` , `datum`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL4`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`PassagiersVliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`VrachtenVliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`VrachtenVliegtuig` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`VrachtenVliegtuig`
(
  `registratieNr` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`registratieNr`),
  CONSTRAINT `fk_JiSQL3`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`Vliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`VrachtenVlucht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`VrachtenVlucht` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`VrachtenVlucht`
(
  `lading` INT NOT NULL,
  `vluchtNr` VARCHAR
(45) NOT NULL,
  `datum` DATE NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`lading`, `vluchtNr`, `datum`),
  INDEX `fk_JiSQL1_idx`
(`vluchtNr` ASC, `datum` ASC),
  INDEX `fk_JiSQL5_idx`
(`registratieNr` ASC),
  CONSTRAINT `fk_JiSQL1`
    FOREIGN KEY
(`vluchtNr` , `datum`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`Vlucht`
(`vluchtNr` , `datum`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL5`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`VrachtenVliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`Klasse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`Klasse` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`Klasse`
(
  `klasse` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`klasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchtvaartmaatschappijGAII`.`KlassePassagiersVliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchtvaartmaatschappijGAII`.`KlassePassagiersVliegtuig` ;

CREATE TABLE
IF NOT EXISTS `LuchtvaartmaatschappijGAII`.`KlassePassagiersVliegtuig`
(
  `klasse` VARCHAR
(45) NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  `aantalStoelen` INT NULL,
  PRIMARY KEY
(`klasse`, `registratieNr`),
  INDEX `fk_JiSQL8_idx`
(`registratieNr` ASC),
  INDEX `fk_JiSQL7_idx`
(`klasse` ASC),
  CONSTRAINT `fk_JiSQL7`
    FOREIGN KEY
(`klasse`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`Klasse`
(`klasse`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL8`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `LuchtvaartmaatschappijGAII`.`PassagiersVliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
