-- MySQL Script generated by MySQL Workbench
-- Fri May  4 17:49:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema luchtvaartmaatschappijGP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `luchtvaartmaatschappijGP`
;

-- -----------------------------------------------------
-- Schema luchtvaartmaatschappijGP
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `luchtvaartmaatschappijGP` DEFAULT CHARACTER
SET utf8 ;
USE `luchtvaartmaatschappijGP`
;

-- -----------------------------------------------------
-- Table `luchtvaartmaatschappijGP`.`VliegtuigType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luchtvaartmaatschappijGP`.`VliegtuigType` ;

CREATE TABLE
IF NOT EXISTS `luchtvaartmaatschappijGP`.`VliegtuigType`
(
  `type` VARCHAR
(45) NOT NULL,
  `maxLading` INT NOT NULL,
  PRIMARY KEY
(`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luchtvaartmaatschappijGP`.`Klasse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luchtvaartmaatschappijGP`.`Klasse` ;

CREATE TABLE
IF NOT EXISTS `luchtvaartmaatschappijGP`.`Klasse`
(
  `klasse` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`klasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luchtvaartmaatschappijGP`.`Vliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luchtvaartmaatschappijGP`.`Vliegtuig` ;

CREATE TABLE
IF NOT EXISTS `luchtvaartmaatschappijGP`.`Vliegtuig`
(
  `registratieNr` VARCHAR
(45) NOT NULL,
  `aantalStewardessen` INT NULL,
  `type` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`registratieNr`),
  INDEX `fk_JiSQL2_idx`
(`type` ASC),
  CONSTRAINT `fk_JiSQL2`
    FOREIGN KEY
(`type`)
    REFERENCES `luchtvaartmaatschappijGP`.`VliegtuigType`
(`type`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luchtvaartmaatschappijGP`.`Vlucht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luchtvaartmaatschappijGP`.`Vlucht` ;

CREATE TABLE
IF NOT EXISTS `luchtvaartmaatschappijGP`.`Vlucht`
(
  `vluchtNr` VARCHAR
(45) NOT NULL,
  `datum` DATE NOT NULL,
  `onverkochteStoelen` INT NULL,
  `lading` INT NULL,
  `vluchtType` VARCHAR
(45) NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`vluchtNr`, `datum`),
  INDEX `fk_JiSQL3_idx`
(`registratieNr` ASC),
  CONSTRAINT `fk_JiSQL3`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `luchtvaartmaatschappijGP`.`Vliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luchtvaartmaatschappijGP`.`KlasseVliegtuig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luchtvaartmaatschappijGP`.`KlasseVliegtuig` ;

CREATE TABLE
IF NOT EXISTS `luchtvaartmaatschappijGP`.`KlasseVliegtuig`
(
  `klasse` VARCHAR
(45) NOT NULL,
  `registratieNr` VARCHAR
(45) NOT NULL,
  `aantalStoelen` INT NOT NULL,
  PRIMARY KEY
(`klasse`, `registratieNr`),
  INDEX `fk_JiSQL4_idx`
(`registratieNr` ASC),
  INDEX `fk_JiSQL1_idx`
(`klasse` ASC),
  CONSTRAINT `fk_JiSQL1`
    FOREIGN KEY
(`klasse`)
    REFERENCES `luchtvaartmaatschappijGP`.`Klasse`
(`klasse`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL4`
    FOREIGN KEY
(`registratieNr`)
    REFERENCES `luchtvaartmaatschappijGP`.`Vliegtuig`
(`registratieNr`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
