-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 10:21:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema perosneel_warenhuis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `perosneel_warenhuis`
;

-- -----------------------------------------------------
-- Schema perosneel_warenhuis
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `perosneel_warenhuis` DEFAULT CHARACTER
SET utf8 ;
USE `perosneel_warenhuis`
;

-- -----------------------------------------------------
-- Table `perosneel_warenhuis`.`Gebouw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perosneel_warenhuis`.`Gebouw` ;

CREATE TABLE
IF NOT EXISTS `perosneel_warenhuis`.`Gebouw`
(
  `code` VARCHAR
(16) NOT NULL,
  `locatie` VARCHAR
(45) NULL,
  PRIMARY KEY
(`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perosneel_warenhuis`.`Afdeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perosneel_warenhuis`.`Afdeling` ;

CREATE TABLE
IF NOT EXISTS `perosneel_warenhuis`.`Afdeling`
(
  `code` VARCHAR
(16) NOT NULL,
  `naam` VARCHAR
(45) NULL,
  `onderafdelingVan` VARCHAR
(16) NULL,
  `locatie` VARCHAR
(16) NOT NULL,
  PRIMARY KEY
(`code`),
  INDEX `fk_JiSQL_idx`
(`onderafdelingVan` ASC),
  INDEX `fk_JiSQL1_idx`
(`locatie` ASC),
  CONSTRAINT `fk_JiSQL`
    FOREIGN KEY
(`onderafdelingVan`)
    REFERENCES `perosneel_warenhuis`.`Afdeling`
(`code`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL1`
    FOREIGN KEY
(`locatie`)
    REFERENCES `perosneel_warenhuis`.`Gebouw`
(`code`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perosneel_warenhuis`.`Werknemer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perosneel_warenhuis`.`Werknemer` ;

CREATE TABLE
IF NOT EXISTS `perosneel_warenhuis`.`Werknemer`
(
  `personeelnummer` INT NOT NULL AUTO_INCREMENT,
  `voorletters` VARCHAR
(45) NULL,
  `achternaam` VARCHAR
(45) NULL,
  `beginAfdeling` VARCHAR
(16) NULL,
  `werkAfdeling` VARCHAR
(16) NOT NULL,
  PRIMARY KEY
(`personeelnummer`),
  INDEX `fk_JiSQL2_idx`
(`beginAfdeling` ASC),
  INDEX `fk_JiSQL3_idx`
(`werkAfdeling` ASC),
  CONSTRAINT `fk_JiSQL2`
    FOREIGN KEY
(`beginAfdeling`)
    REFERENCES `perosneel_warenhuis`.`Afdeling`
(`code`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL3`
    FOREIGN KEY
(`werkAfdeling`)
    REFERENCES `perosneel_warenhuis`.`Afdeling`
(`code`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perosneel_warenhuis`.`WerknemerAfdeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perosneel_warenhuis`.`WerknemerAfdeling` ;

CREATE TABLE
IF NOT EXISTS `perosneel_warenhuis`.`WerknemerAfdeling`
(
  `personeelnummer` INT NOT NULL,
  `afdelingCode` VARCHAR
(16) NOT NULL,
  `startDatum` DATE NOT NULL,
  `eindDatum` DATE NULL,
  PRIMARY KEY
(`personeelnummer`, `afdelingCode`),
  INDEX `fk_JiSQL5_idx`
(`afdelingCode` ASC),
  INDEX `fk_JiSQL4_idx`
(`personeelnummer` ASC),
  CONSTRAINT `fk_JiSQL4`
    FOREIGN KEY
(`personeelnummer`)
    REFERENCES `perosneel_warenhuis`.`Werknemer`
(`personeelnummer`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL5`
    FOREIGN KEY
(`afdelingCode`)
    REFERENCES `perosneel_warenhuis`.`Afdeling`
(`code`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
