-- MySQL Script generated by MySQL Workbench
-- Tue Apr 17 12:47:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Linkedin_berichten
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Linkedin_berichten` ;

-- -----------------------------------------------------
-- Schema Linkedin_berichten
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Linkedin_berichten` DEFAULT CHARACTER SET utf8 ;
USE `Linkedin_berichten` ;

-- -----------------------------------------------------
-- Table `Linkedin_berichten`.`Gebruiker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkedin_berichten`.`Gebruiker` ;

CREATE TABLE IF NOT EXISTS `Linkedin_berichten`.`Gebruiker` (
  `email` VARCHAR(45) NOT NULL,
  `naam` VARCHAR(45) NULL,
  `plaats` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkedin_berichten`.`Bericht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkedin_berichten`.`Bericht` ;

CREATE TABLE IF NOT EXISTS `Linkedin_berichten`.`Bericht` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP(10) NOT NULL,
  `text` VARCHAR(45) NULL,
  `reactieId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_JiSQL4_idx` (`reactieId` ASC),
  CONSTRAINT `fk_JiSQL4`
    FOREIGN KEY (`reactieId`)
    REFERENCES `Linkedin_berichten`.`Bericht` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkedin_berichten`.`GebruikerGebruiker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkedin_berichten`.`GebruikerGebruiker` ;

CREATE TABLE IF NOT EXISTS `Linkedin_berichten`.`GebruikerGebruiker` (
  `email` VARCHAR(45) NOT NULL,
  `email1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`, `email1`),
  INDEX `fk_JiSQL1_idx` (`email1` ASC),
  INDEX `fk_JiSQL_idx` (`email` ASC),
  CONSTRAINT `fk_JiSQL`
    FOREIGN KEY (`email`)
    REFERENCES `Linkedin_berichten`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL1`
    FOREIGN KEY (`email1`)
    REFERENCES `Linkedin_berichten`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkedin_berichten`.`GebruikerBericht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkedin_berichten`.`GebruikerBericht` ;

CREATE TABLE IF NOT EXISTS `Linkedin_berichten`.`GebruikerBericht` (
  `email` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`email`, `id`),
  INDEX `fk_JiSQL3_idx` (`id` ASC),
  INDEX `fk_JiSQL2_idx` (`email` ASC),
  CONSTRAINT `fk_JiSQL2`
    FOREIGN KEY (`email`)
    REFERENCES `Linkedin_berichten`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JiSQL3`
    FOREIGN KEY (`id`)
    REFERENCES `Linkedin_berichten`.`Bericht` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
